### ISSUE TITLE
TypeError: requestUntilSuccess() got an unexpected keyword argument 'sleepTime' 

### ISSUE THREAD

**Issue by 982968** [Denis-Oakley/jdAutoShopping#1]
TypeError: requestUntilSuccess() got an unexpected keyword argument 'sleepTime' 你好，请问这是怎么回事呢

**Comment by 982968** [comment]
还想请问下cookie直接复制到{"cookie_1": “”就可以吗？

**Comment by 982968** [comment]
![image](https://user-images.githubusercontent.com/38133470/74247071-7a0a2980-4d20-11ea-9d44-b314867a4508.png)

**Comment by StephanoGeorge** [comment]
> 还想请问下cookie直接复制到{"cookie_1": “”就可以吗？

是使用真实的替换 cookie_1

**Comment by StephanoGeorge** [comment]
可能是下载了只提交一半的版本，重新下载最新的

**Comment by 982968** [comment]
好的，我再下载试试，谢谢

**Comment by 982968** [comment]
商品id也需要是 id:true  这样的键值对么

**Comment by 982968** [comment]
> 可能是下载了只提交一半的版本，重新下载最新的

好的，我再下载试试，谢谢

商品id也需要是id：true这样的键值对么

**Comment by StephanoGeorge** [comment]
> 商品id也需要是 id:true 这样的键值对么

对，主要为了编辑时去重

**Comment by 982968** [comment]
还是会像截图那样。。。。

**Comment by StephanoGeorge** [comment]
> 还是会像截图那样。。。。

好像我忘记 push 了，再下载吧

**Comment by StephanoGeorge** [comment]
已经 push

**Comment by 982968** [comment]
![image](https://user-images.githubusercontent.com/38133470/74250521-b2f8cd00-4d25-11ea-9c2e-19610da30310.png)

**Comment by 982968** [comment]
你好，正常运行界面是怎么样的哦

**Comment by StephanoGeorge** [comment]
监控正常不输出，想要看的话，注释 `monitor.py` 的 47 行：`logLvl=logging.DEBUG`

**Comment by 982968** [comment]
好的，非常感谢大佬指导👍

**Comment by 982968** [comment]
试了一个有货的，他会一直加入购物车，而且不会提交订单😂
![image](https://user-images.githubusercontent.com/38133470/74251855-b9884400-4d27-11ea-8cc4-0c82343f57c9.png)

**Comment by StephanoGeorge** [comment]
不太清楚可能是什么问题，下单测试得少，怕账户受限，我明天再看看，睡觉

**Comment by 982968** [comment]
好的，大佬辛苦了，晚安

**Comment by StephanoGeorge** [comment]
最新的版本，我测试下单没问题了

**Comment by 982968** [comment]
我测试了一下，会一次性加入几件商品到购物车然后下单，而且停不下来，会一直下单😂

**Comment by StephanoGeorge** [comment]
这是这么设计的，主要为抢口罩设计的

**Comment by 982968** [comment]
你好，请问在哪个文件改下单数量呢，有好多口罩都限购一件😂

**Comment by StephanoGeorge** [comment]
> 你好，请问在哪个文件改下单数量呢，有好多口罩都限购一件joy

没设计，不过这样的话，我试试加功能。发几个限购商品的id，我看下
