### ISSUE TITLE
请教几个问题

### ISSUE THREAD

**Issue by Drac4ry** [Denis-Oakley/jdAutoShopping#2]
你好
一开始运行时候总提示keyerror：areaId，我猜想可能是config.json文件中config函数缺少areaId值，我就加上了，错误解决。
![image](https://user-images.githubusercontent.com/58971504/75089279-1e4a6680-5592-11ea-8b72-22353aadbea1.png)

运行之后不动，看了下已关闭的那个提问，把商品换成一个有库存的正常商品，出现以下错误，我看得脑壳昏
![image](https://user-images.githubusercontent.com/58971504/75089103-5fda1200-5590-11ea-8709-2ee4597b60d6.png)
于是来问一下大佬，这是怎么回事
![image](https://user-images.githubusercontent.com/58971504/75089154-fad2ec00-5590-11ea-9860-0dc1aa28c3b1.png)
另：
我areaid是从下面这个参数里找的，cookie里areaid只有省份，这样对吗
![image](https://user-images.githubusercontent.com/58971504/75089268-04a91f00-5592-11ea-92d5-8282fcd9f849.png)

**Comment by StephanoGeorge** [comment]
这个异常应该已经修复了, 试试新版, 配置文件换成了 yaml, 逻辑也改了
`areaId` 请看 https://github.com/tychxn/jd-assistant/wiki/3.-%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98
看readme, 监控正常不会输出

**Comment by Drac4ry** [comment]
但是最新版似乎没有yaml这个配置文件...

**Comment by StephanoGeorge** [comment]
Sorry, 忘记添加了, 现在再试试

**Comment by Drac4ry** [comment]
折腾了好一会弄好了，现在已经可以正常监控，感谢
![image](https://user-images.githubusercontent.com/58971504/75095454-c92d4580-55cf-11ea-915b-7265ef21680f.png)

就这一会的功夫，大佬又更新好几个版本了，强

**Comment by StephanoGeorge** [comment]
好, 其实没修改多少代码
