### ISSUE TITLE
使用说明太简单了，对我们新手来说太难了

### ISSUE THREAD

**Issue by jy024929** [Denis-Oakley/jdAutoShopping#3]
可不可以写的更详细点，像小学生一样，一步一步写

**Comment by StephanoGeorge** [comment]
有些地方不好用书面语描述, 你哪里看不懂
不为已有一堆教程的方面提供教程, 如: 如何运行 `.py` 文件, 如何编辑 `.yaml` 文件,  如何使用开发者工具

**Comment by jy024929** [comment]
获取下单相关的值
向购物车中加入任意商品, 点击去结算, 在订单结算页面打开开发者工具, 在 Console 中执行以下代码, 将输出复制至配置文件:

let eid = $('#eid').val();
let fp = $('#fp').val();
let trackId = getTakId();
console.log(`eid: ${eid}\nfp: ${fp}\ntrackId: ${trackId}\n`);
问题1.怎么打开开发者工具，问题2.配置文件是哪个，复制在哪里

获取 cookies
在任意京东页面打开开发者工具, 刷新, 查看网络请求, 过滤 passport.jd.com/loginservice.aspx, 将请求 cookie 复制至配置文件
问题1.怎么查看网络请求
问题2.如何过滤passport.jd.com/loginservice.aspx,
问题3.cookie是什么要举例子，复制什么
问题4.配置文件是哪个，复制到里面的哪里

测试下单
按照说明编辑 testOrder.py 文件, 并运行它
这个文件里面的说明完全看不懂，最好举几个例子。

监控库存正常或超时都不会输出, 要自定义请修改代码
这句话什么意思，如何修改代码，什么脚输出，也需要举个例子

**Comment by StephanoGeorge** [comment]
> 怎么打开开发者工具
 
请搜索如何使用开发者工具

> 配置文件是哪个，复制在哪里

`config.yaml`, 看其中的注释,  需要了解 yaml 语法

> 怎么查看网络请求,  如何过滤passport.jd.com/loginservice.aspx

请搜索如何使用开发者工具

> cookie是什么要举例子，复制什么

所有请求 cookie

> 按照说明编辑 testOrder.py 文件, 并运行它, 这个文件里面的说明完全看不懂

先配置好再看看

> 这句话什么意思，如何修改代码，什么脚输出

请先体验一下命令行(终端)使用, 修改代码需要有 Python 基础
