### ISSUE TITLE
eip fp trackId Cookie都填写进去了，出现这个错误怎么解决

### ISSUE THREAD

**Issue by caterilr** [Denis-Oakley/jdAutoShopping#4]
Traceback (most recent call last):
  File "D:/jdAutoShopping-master/main.py", line 3, in <module>
    import glb
  File "D:\jdAutoShopping-master\glb.py", line 1, in <module>
    from ruamel import yaml
ModuleNotFoundError: No module named 'ruamel'

Process finished with exit code 1

**Comment by StephanoGeorge** [comment]
翻译过来是模组未安装, 如何安装请搜索

**Comment by caterilr** [comment]
这个是模组吗？ruamel，

**Comment by caterilr** [comment]
UnicodeDecodeError: 'gbk' codec can't decode byte 0xa8 in position 22: illegal multibyte sequence
安装模组后出现了新的错误代码

**Comment by StephanoGeorge** [comment]
不要使用GBK编码, 使用UTF-8, 使用代码编辑器编辑来确保编码正确
