### ISSUE TITLE
不行啊，用PyCharm编辑还是提示UnicodeDecodeError: 'gbk' codec can't decode

### ISSUE THREAD

**Issue by caterilr** [Denis-Oakley/jdAutoShopping#5]
这是完整的日志
下载下来的代码直接解压，将 configTemplate.yaml 文件更名为 config.yaml, 不编辑直接运行main.py就显示这个
D:\Python38\python.exe D:/JD_buy/main.py
Traceback (most recent call last):
  File "D:/JD_buy/main.py", line 7, in <module>
    glb.init()
  File "D:\JD_buy\glb.py", line 43, in init
    configStr = file.read()
UnicodeDecodeError: 'gbk' codec can't decode byte 0xa8 in position 22: illegal multibyte sequence

Process finished with exit code 1

**Comment by StephanoGeorge** [comment]
Windows 默认编码还是该淘汰的 GBK, 更新了一下, 强制使用 UTF-8 编码读取

**Comment by caterilr** [comment]
感谢大佬，解决问题了,把系统强制UTF-8了

**Comment by caterilr** [comment]
> 
> 
> Windows 默认编码还是该淘汰的 GBK, 更新了一下, 强制使用 UTF-8 编码读取
大佬testOrder.py的KEY是哪个？是cookie的全段吗？全复制进去提示错误，Cookie中的user-key=后面的复制进去也不对
# 初始化
glb.init()

id = ''  # 账户在 config.yaml 中的 key

**Comment by StephanoGeorge** [comment]
configTemplate.yaml 当中出现的 me/another
